### ISSUE TITLE
Supressions ignored by VisualStudio add-in

### ISSUE THREAD

**Issue by dreieier** [VioletGiraffe/cppcheck-vs-addin#102]
In a VisualStudio C++ project I want to exclude files from a library from being checked. All files start with "juce_". In the CppCheck settings under "Edit Global supressions" I added "^juce_.*\.cpp$" and "^juce_.*\.h$" in the file list. Additionally, in the directory list, I added regexes in the style of ".*juce.*".
The supressions seem to be ignored and all the files I want to exclude are checked.

**Comment by VioletGiraffe** [comment]
Your regex syntax is simply incorrect. These are C# regexes. Not the syntax of the pre-existing default  suppressions. If you want to exclude files named "juce_*.*" (don't see a point writing the same filter twice for .cpp and .h), then the filter is this: `^juce_.*\.$`
Same with paths. Use the default ones for reference.

**Comment by dreieier** [comment]
Thanks for the quick reply and sorry for my malformed regex syntax. I forgot the extra slashes for escaping in the post. Please let me correct it:<br>In the settings I have: <code>^juce_.*\\.cpp$</code>, <code>^juce_.*\\.h$</code> to supress the files and <code>.\*juce.\*</code> for the root directory of the library.<br>Of course, there is no use for the same filter on .cpp and .h and also the directory filter is redundant. I just tried different combinations, always following the style of the default filters, but none of them worked.<br>
By the way, your post is suffering from the problem as mine: The <code>*</code> before the <code>$</code> has been eaten.

**Comment by VioletGiraffe** [comment]
It's not eaten, I forgot it :)
So does it work now?

**Comment by dreieier** [comment]
No, it doesn't... All #included .h files in the lib are checked and also .cpp files.

**Comment by VioletGiraffe** [comment]
You don't have `*` in your file filters. Try this, as per my edited reply:

`^juce_.*\.*$`

**Comment by dreieier** [comment]
This was among the things I tried, still the juce pours out.

**Comment by VioletGiraffe** [comment]
Do .cpp files pour out, or just headers?

**Comment by dreieier** [comment]
Now that the filter is <code>^juce_.*\\.\*$</code> I see only .h files.

**Comment by VioletGiraffe** [comment]
Aha! You can't get rid of messages from `juce_*.h` files just like that. Why? Because they are included into _your_ .cpp files, either directly or through other headers.

**Comment by dreieier** [comment]
Yes, exactly. Should the filter supress these?

**Comment by VioletGiraffe** [comment]
No, that's the point, it should not. This filter, the one you've been asking about so far, filters the files that `cppcheck` will or will not be run on.

**Comment by dreieier** [comment]
Ok, I missed that point. My understanding was the filter would supress any matching files, regardless how they come in scope.<br>
Is it possible to apply a filter in that way? Checking all the headers on every run is time consuming and also I don't want to touch the library to fix what cppcheck is reporting.<br>
I tried -iD:\Dev\C++\Lib\juce in the command line, with no sucess.

**Comment by VioletGiraffe** [comment]
Again: it does not check the headers, it checks your cpp files. You should suppress any warnings from juce headers, but you can't avoid getting those warnings in the first place.

**Comment by VioletGiraffe** [comment]
Closing as not an issue.
