### ISSUE TITLE
Cannot install the plugin when VS2012 and VS2013 are both installed

### ISSUE THREAD

**Issue by SanderBouwhuis** [VioletGiraffe/cppcheck-vs-addin#103]
I have a machine with both VS2012 and VS2013 installed side by side. When I try to install the plugin, it only installs it for VS2012.

Any info on how to also add it to VS2013?

**Comment by VioletGiraffe** [comment]
I have VS 2012, 2013 and 2015 Preview, and the plugin can be installed for all of them - I've just tested.
If 2013 is not in the list, chances are this version of the plugin is already installed there.

**Comment by SanderBouwhuis** [comment]
I think there is a bug of some sorts. When I run the CppcheckPlugin.vsix it ONLY shows me VS012 as option. Here is a screenshot of my desktop with BOTH VS2012 and VS2013 installed:
<a href="http://s886.photobucket.com/user/shbouwhuis/media/VS2012VS2013PluginBug.png.html" target="_blank"><img src="http://i886.photobucket.com/albums/ac64/shbouwhuis/th_VS2012VS2013PluginBug.png" border="0" alt="VS2012 + VS2013 Plugin Bug photo VS2012VS2013PluginBug.png" style=""></a>

Is it possible to install this manually so I can get this to run? If so, how?

**Comment by VioletGiraffe** [comment]
Hm. I don't know what's wrong.
As far as I know, there's no other way to install the extension. I suppose if you know which register keys to create you can do that, but I don't know the procedure.
By the way, the list of extensions in the VS 2013 About box on your screenshot does not fit the window, a couple last items are invisible. So I can't conclude that cppcheck add-in is not already installed.

**Comment by SanderBouwhuis** [comment]
The list of extensions also include:
Release Management for Visual Studio
Visual Assist
Windows Phone 8.1 SDK Interation 1.0

It's a shame the plugin doesn't work.
