### ISSUE TITLE
Cannot check projects located on UNC paths

### ISSUE THREAD

**Issue by Dmitry-Me** [VioletGiraffe/cppcheck-vs-addin#117]
The problem is because of `cleanPath()` function which violently removes all the leading backslashes and a neat `\\machine\path` turns into `machine\path`.

I'm not sure how to deal with this. Why are leading backslashes removed in the first place?

**Comment by VioletGiraffe** [comment]
Don't know. I've set a breakpoint in that line, run a couple tests and never hit the breakpoint. But, apparently, I did need it in the past. Possibly for relative paths? Combining a base path and relative path into a new absolute one?..

**Comment by VioletGiraffe** [comment]
It could be that removing leading backslashes is no longer necessary since I started using API functions for managing paths, rather than mechanically concatenating strings.

**Comment by Dmitry-Me** [comment]
It's a bit harder than I expected. Not only the add-in but also Cppheck treat UNC paths incorrectly - Cppcheck outputs `\\magic\path` as `\magic\path`. I guess it's worth waiting until a new release of Cppcheck appears where this is resolved.

**Comment by VioletGiraffe** [comment]
Do you have a reason to believe this will be resolved in the new release?

**Comment by Dmitry-Me** [comment]
Yes, I've submitted one PR which was merged and then another with further fixes that is pending.
