### ISSUE TITLE
failure to run analysis if arguments string is too long

### ISSUE THREAD

**Issue by gkelly-si** [VioletGiraffe/cppcheck-vs-addin#135]
I don't really know what is too long - this seems to suggest 8192 or 32767: http://blogs.msdn.com/b/oldnewthing/archive/2003/12/10/56028.aspx

But what I am seeing is that if I have a large project and have quite a deep structure then the length of the command string is too long and will raise an error:

    Exception occurred in cppcheck add-in: System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
    at System.Diagnostics.Process.Start()
    at VSPackage.CPPCheckPlugin.ICodeAnalyzer.startAnalyzerProcess(String analyzerExePath, String arguments

You should be able to reproduce it just by adding a loop to getProjectFiles() I think - i.e. just add the same file over and over again, so that the path is duplicated in the argument strings. In my real project, the argument string length is 45135.

It was originally my intention to debug this and submit a fix but it seems to me that this might be a design issue for now: maybe getProjectFiles() could stop at some limit (configurable?) and pass a flag back to checkProjects() to handle the project in batches? Some adjustment would then be needed to runAnalysis() to not clear the output pane and instead amalgamate results, by the looks of it. There is also the problem that getProjectFiles() doesn't know the length of the non-file part of the argument string (e.g. the settings and the suppressions) so limiting the number of files isn't really a catch-all solution anyway. So I opted for a bug report instead :).

**Comment by VioletGiraffe** [comment]
Yeah, I suspected it'd happen sooner or later... It is indeed a design flaw.

**Comment by gkelly-si** [comment]
I had a look at the cppcheck help documentation, it allows a --file_list argument instead of getting the entire list as an argument. I guess maybe designed to work around this exact issue.

I've put together a change here that writes to a temp file and passes that instead, and it's happily scanning my entire project now. I'll fork and submit a pull request shortly.

**Comment by VioletGiraffe** [comment]
Nice! Please do submit it.
