### ISSUE TITLE
Where options are saved ?

### ISSUE THREAD

**Issue by fjautard** [VioletGiraffe/cppcheck-vs-addin#149]
Dear all,

I'm using CppCheck add-in and it is great tool. Thanx.

[QUESTION]
I'm looking for where options are saved.
I found project options but not cppcheck messages list: in Cppcheck settings, I click on "Display all cppcheck messages"; I uncheck information, portability and style. 
Where are they stored ? 
Is it in cppcheck settings, in ccpcheck add-in, in visual studio add-ins settings ?
Please, help me.

TIA
Francois

**Comment by clcaalu** [comment]
Is there a reply to this question?

**Comment by VioletGiraffe** [comment]
@clcaalu : the settings are stored in `Properties.Settings.Default`. I don't know which specific storage backs up this API.
