### ISSUE TITLE
Not working in Visual Studio 2013 Community Edition

### ISSUE THREAD

**Issue by frazzyfin** [VioletGiraffe/cppcheck-vs-addin#151]
Plugin is installed.
Menu options appear in TOOLS.
Clicking either one does nothing.

**Comment by VioletGiraffe** [comment]
I have the same issue on my home PC but am unable to debug it for technical reasons. And it doesn't occur on the machines where I can debug. So I'm puzzled for the moment.

**Comment by VioletGiraffe** [comment]
Try this: http://www.nullskull.com/faq/1679/how-to-reset-all-settings-restore-toolbox-items-refresh-visual-studio.aspx

**Comment by frazzyfin** [comment]
Unfortunately that didn't work. Still the same behaviour (or lack of behaviour)

**Comment by VioletGiraffe** [comment]
That's odd because if I launch debug on the same machine in the same VS version, it works. Debug launches a clean "experimental" instance of Visual Studio, which is why I assumed reset would work, too.

**Comment by frazzyfin** [comment]
How do you launch VS debug mode?

**Comment by VioletGiraffe** [comment]
Install Visual Studio SDK, open this project and press F5.

**Comment by rhayne04** [comment]
I am having a similar issue, except with VS 2013 Professional.  After I did the reset all settings thing, it now says "The 'CPPCheckPluginPackage' di not load correctly.  Checking the log, it says CreateInstance failed.

**Comment by VioletGiraffe** [comment]
I think it's no longer compatible with VS 2013 after the recent changes and fixing VS 2017 issues. If you know how to add the missing dependencies and fine-tune the references, please do.
