### ISSUE TITLE
Dark theme not entirely supported

### ISSUE THREAD

**Issue by johron** [VioletGiraffe/cppcheck-vs-addin#152]
In Visual Studio 2015, the add-in is still displayed in bright white despite that the editor is set to 'dark-theme'.

**Comment by VioletGiraffe** [comment]
Yes, I have researched this issue and there's no simple way to apply the VS theme. I'd have to manually apply all the colors and styles.
P. S. If anyone wants to contribute a fix for this problem - be my guest :)

**Comment by tekesh** [comment]
Thanks for the quick reply :)

Where would the colors be applied? I was thinking i might look into it if i
get some time to spare for this.

No promises, but i'd love to fix it if i can figure out how.

//Johan

**Comment by VioletGiraffe** [comment]
I didn't get that far as to know _how_ it's done, so Google it is, I guess. I was thinking there would be a magic flag / attribute "make this window use the current VS theme", but no. I did not look further once I found out there's no easy way.

**Comment by VioletGiraffe** [comment]
Partially implemented. You can refer to the commit to see how it's done.
Missing parts:
* item hover cursor;
* row / column separator lines;
* resizing a column also triggers a wrong color.

**Comment by lederernc** [comment]
I added a PR for supporting dark mode.

**Comment by lederernc** [comment]
this can be closed now.

**Comment by VioletGiraffe** [comment]
Yep. Thank you.
