### ISSUE TITLE
C++ projects are not identified as such when running in VS 2017 RC

### ISSUE THREAD

**Issue by VioletGiraffe** [VioletGiraffe/cppcheck-vs-addin#156]
The plugin fails in VS 2017 RC because the following line in `isVisualCppProject()` always returns `null`:
```projectObjectType.GetInterface("Microsoft.VisualStudio.VCProjectEngine.VCProject");```

**Comment by VioletGiraffe** [comment]
Suggested solutions: http://stackoverflow.com/questions/41180351/how-to-determine-whether-or-not-envdte-project-object-represents-a-c-c-project

**Comment by Dmitry-Me** [comment]
What interfaces are there when you invoke `Type.GetInterfaces()`?

**Comment by VioletGiraffe** [comment]
I'll tell you tomorrow (unless I forget) - don't have 2017 on the home PC yet.
I started working on the fix, but it turned out to be very difficult (tedious) to implement because _someone_ (I don't mean you - I don't know who written that piece of code, and I don't want to know) used `dynamic` and `object` types a lot for passing the project instance around, and they even mean different types in different parts of the code, and because of that I can't easily refactor it into `EnvDTE.Project`.

**Comment by Dmitry-Me** [comment]
Most likely that someone was me. Yes, I agree that having strong typing is good but it all started because different versions of Visual Studio use identical yet formally different sets of interfaces and so having a plugin which supports all of them requires either duc typing or a lot of thunk assemblies and a whole set of Visual Studio SDKs  (and Visual Studios too) to build the project.

**Comment by VioletGiraffe** [comment]
Hmm. Sorry, I wasn't aware of that problem.

**Comment by Dmitry-Me** [comment]
Here it is https://github.com/VioletGiraffe/cppcheck-vs-addin/pull/12

**Comment by VioletGiraffe** [comment]
Right... So I can't just use the `Project` type?

**Comment by Dmitry-Me** [comment]
If it's part of version-specific assembly - no, you cannot make use of it for strong typing. That's why there's `dynamic`.

**Comment by meragrin** [comment]
If the fast project loading experimental is disabled, it works.

https://stackoverflow.com/questions/43321647/iterating-vcfilter-tree-in-visual-studio-2017
https://blogs.msdn.microsoft.com/vcblog/2016/10/05/faster-c-solution-load-with-vs-15/

**Comment by VioletGiraffe** [comment]
Interesting, thanks. Still, I believe that the proposed changes to the code should allow the add-in to circumvent this issue.
