### ISSUE TITLE
Running a check results in "Sequence contains no elements"

### ISSUE THREAD

**Issue by x29a** [VioletGiraffe/cppcheck-vs-addin#157]
Hi, on Windows 7 64bit, SP1, Visual Studio 2015, 2013 and 2010 installed.

cppcheck-vs-addin version is 1.3.3.

I open a solution, set a startup project, then click Tools -> "Check current project with cppcheck" and i get an error message Box with title "Microsoft Visual Studio" and text "Sequence contains no elements", in both, VS 2013 and VS 2015.

![cppcheck_vs_addin](https://cloud.githubusercontent.com/assets/204177/22501324/a07e3a04-e868-11e6-86fe-1116ebe9a612.png)

I uninstalled cppcheck 1.77 64bit and tried with cppcheck x86 1.77 and went back to 1.73 (all x86), the error stays the same.

The installation went without errors, looking at ActivityLog.xml, the addin seems to load correctly. Any other hints?

**Comment by Dmitry-Me** [comment]
Does the project contain and .cpp or .c files?

**Comment by Dmitry-Me** [comment]
This change should get you a meaningful message instead https://github.com/VioletGiraffe/cppcheck-vs-addin/commit/ce2c5aa73eadb60f923cb148e684501a29ba9181

**Comment by x29a** [comment]
Thanks for your feedback, 

yes the projects contain source (.cpp) and header (.h) files, but sorted under filters (kind of logical folders). I compiled master and re-enabled your change (you reverted it with [4d3af3a4c7da88a7a8264ef4de0d5062f53895a1](https://github.com/VioletGiraffe/cppcheck-vs-addin/commit/4d3af3a4c7da88a7a8264ef4de0d5062f53895a1)) and it is indeed complaining that no suitable files are found in the selected projects.

**Comment by VioletGiraffe** [comment]
I  have never tested it on a project with filters, maybe the plugin doesn't iterate them properly?

**Comment by x29a** [comment]
It does not seem to be the filter, since when moving some files directly under the project, the error is still the same. Its strange, since others seem to use the addin with VS2015 and no problems.

How would i debug it? When running the solution in VS2015 and setting the Debug option to "Start external program" and select the 14.0 devenv (according to [REAMDE.md](https://github.com/VioletGiraffe/cppcheck-vs-addin/blob/master/README.md), the Test VS opens, but the add-in is not available.

**Comment by x29a** [comment]
I noticed it has to do with one of my property sheets, so it might be related to issue #73. Debugging hints still appreciated.
