### ISSUE TITLE
VS-Addin : Visual Studio 2017 Community : unable to install

### ISSUE THREAD

**Issue by cdemez** [VioletGiraffe/cppcheck-vs-addin#161]
Hi,

I cannot install the VS Add in for VS 2017 community. It seems expected ?

I join the log:

`29/03/2017 13:49:06 - Microsoft VSIX Installer
29/03/2017 13:49:06 - -------------------------------------------
29/03/2017 13:49:06 - vsixinstaller.exe version:
29/03/2017 13:49:06 - 15.0.26228.9 built by: D15RTWSVC
29/03/2017 13:49:06 - -------------------------------------------
29/03/2017 13:49:06 - Command line parameters:
29/03/2017 13:49:06 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\CDEMEZ~1.LUC\AppData\Local\Temp\CppcheckPlugin.vsix
29/03/2017 13:49:06 - -------------------------------------------
29/03/2017 13:49:06 - Microsoft VSIX Installer
29/03/2017 13:49:06 - -------------------------------------------
29/03/2017 13:49:06 - Initializing Install...
29/03/2017 13:49:06 - Extension Details...
29/03/2017 13:49:06 - 	Identifier         : 127d8bd3-8cd7-491a-9a63-9b4e89118da9
29/03/2017 13:49:06 - 	Name               : cppcheck add-in
29/03/2017 13:49:06 - 	Author             : -
29/03/2017 13:49:06 - 	Version            : 1.3.3
29/03/2017 13:49:06 - 	Description        : Integration for cppcheck - C/C++ code static analysis tool 
29/03/2017 13:49:06 - 	Locale             : en-US
29/03/2017 13:49:06 - 	MoreInfoURL        : 
29/03/2017 13:49:06 - 	InstalledByMSI     : False
29/03/2017 13:49:06 - 	SupportedFrameworkVersionRange : [4.5,)
29/03/2017 13:49:06 - 
29/03/2017 13:49:06 - 	SignatureState     : Unsigned
29/03/2017 13:49:06 - 	Supported Products : 
29/03/2017 13:49:06 - 		Microsoft.VisualStudio.Pro
29/03/2017 13:49:06 - 			Version : [11.0,14.0]
29/03/2017 13:49:06 - 		Microsoft.VisualStudio.Premium
29/03/2017 13:49:06 - 			Version : [11.0,14.0]
29/03/2017 13:49:06 - 		Microsoft.VisualStudio.Ultimate
29/03/2017 13:49:06 - 			Version : [11.0,14.0]
29/03/2017 13:49:06 - 
29/03/2017 13:49:06 - 	References         : 
29/03/2017 13:49:06 - 		-------------------------------------------------------
29/03/2017 13:49:06 - 		Identifier   : Microsoft.VisualStudio.MPF
29/03/2017 13:49:06 - 		Name         : Visual Studio MPF
29/03/2017 13:49:06 - 		Version      : [11.0,)
29/03/2017 13:49:06 - 		MoreInfoURL  : 
29/03/2017 13:49:06 - 		Nested       : No
29/03/2017 13:49:06 - 
29/03/2017 13:49:06 - Signature Details...
29/03/2017 13:49:06 - 	Extension is not signed.
29/03/2017 13:49:06 - 
29/03/2017 13:49:06 - Searching for applicable products...
29/03/2017 13:49:06 - Found installed product - Global Location
29/03/2017 13:49:06 - Found installed product - Visual Studio Community 2017
29/03/2017 13:49:06 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
`

**Comment by VioletGiraffe** [comment]
I never tried installing it. It did run in 2017 RC when I launched a debugging session, but it didn't work (and still doesn't, for all I know): https://github.com/VioletGiraffe/cppcheck-vs-addin/issues/156

**Comment by cdemez** [comment]
Thanks for the confirmation,

But here I talk about the installation vsix file, FYI.

So, waiting for a fix ;-)

**Comment by VioletGiraffe** [comment]
I understand that! As I said, I never even tried installing it because there's no point (it won't work). But I'll look into it as soon as I have time.

**Comment by drillsar** [comment]
I am guessing this isn't fixed yet

**Comment by VioletGiraffe** [comment]
No. I've figured out the problem the problem, I just need to sit down and implement a fix. It involves replacing bad code with other bad code, so I'm not looking forward to that.

**Comment by VioletGiraffe** [comment]
@drillsar 
This is probably fixed by my today's commit, but that's hardly relevant for you because the extension still doesn't function in VS 2017 because of #156.
