### ISSUE TITLE
Microsoft.Common.CurrentVersion.targets(724,5): error

### ISSUE THREAD

**Issue by Voskrese** [VioletGiraffe/cppcheck-vs-addin#164]
msbuild "CPPCheckPlugin.sln" /p:Configuration=Debug;Platform="Any CPU";PlatformToolset=v140;VisualStudioVersion=14.0 /target:ReBuild /consoleloggerparameters:Verbosity=minimal /p:TargetPlatformVersion=10.0.10240.0

> C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(724,5): error : The OutputPath property  is not set for project 'CPPCheckPlugin.csproj'.  Please check to make sure that you have specified a valid combination  of Configuration and Platform for this project.  Configuration='Debug'  Platform='Any CPU'.  You may be seeing this me ssage because you are trying to build a project without a solution file, and have specified a non-default Configuration  or Platform that doesn't exist for this project. [E:\tools\SRC\cppcheck-vs-addin\CPPCheckPlugin\CPPCheckPlugin.c sproj]

> Ошибка		Extension '127d8bd3-8cd7-491a-9a63-9b4e89118da9' is of the same or lower version than the installed extension. Please make sure that the extension version is higher than that of the installed extension.	CPPCheckPlugin	

редактируем
```
source.extension.vsixmanifest
```
было
```
<Identity Id="127d8bd3-8cd7-491a-9a63-9b4e89118da9" Version="1.3.3" Language="en-US" Publisher="-" />
```
стало
```
<Identity Id="*" Version="1.3.3" Language="en-US" Publisher="-" />
```

> msbuild "CPPCheckPlugin.sln" /p:Configuration=Debug;Platform="Any CPU";PlatformToolset=v140;VisualStudioVersion=14.0 /target:ReBuild /consoleloggerparameters:Verbosity=minimal /p:TargetPlatformVersion=10.0.10240.0
> Microsoft (R) Build Engine версии 14.0.25420.1
> (C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
> 
> Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
>   CPPCheckPlugin ->
>   CPPCheckPlugin ->
>   CPPCheckPlugin -> E:\tools\SRC\cppcheck-vs-addin\CPPCheckPlugin\bin\Debug\CppcheckPlugin.dll
>   Creating intermediate PkgDef file.
>   Creating VSIX Container...
>   CPPCheckPlugin -> E:\tools\SRC\cppcheck-vs-addin\CPPCheckPlugin\bin\Debug\CppcheckPlugin.vsix

ок

**Comment by VioletGiraffe** [comment]
Interesting, thank you. You don't want to create a pull request, I take it?

**Comment by Voskrese** [comment]
hmm...
```
<Identity Id="[14.0,15.0,16.0)" Version="1.3.3" Language="ru-RU" Publisher="-" />
```
[https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017](url)
build ok

**Comment by VioletGiraffe** [comment]
Do you think language is essential here? Can you specify "*" instead?

**Comment by Voskrese** [comment]
просто эксперимент ;)

> just experiment;)
