### ISSUE TITLE
In Visual Studio 2015 Community edition, gets "cannot perform check no valid configuration selected" error

### ISSUE THREAD

**Issue by BrunoMartinGym** [VioletGiraffe/cppcheck-vs-addin#166]
I use Visual Studio 2015 Community edition.  

I installed the last CppCheck version 1.80 on my machine, and the last plugin 1.3.3 and I always get the following error:

"cannot perform check no valid configuration selected"

Does anybody know a workaround?  Must I place some configuration file somewhere?

**Comment by VioletGiraffe** [comment]
No, it's not a configuration file, it refers to the C++ build configuration in Visual Studio, I believe.

**Comment by VioletGiraffe** [comment]
Closing as the report is too vague and no follow-up has been provided.

**Comment by atorstling** [comment]
For what it's worth, I'm getting the same error with the latest build. Can I diagnose it somehow?
