### ISSUE TITLE
Pressing 'Edit active Project suppressions' causes error dialog to be displayed.

### ISSUE THREAD

**Issue by damiandixon** [VioletGiraffe/cppcheck-vs-addin#172]
The content of the dialog is:

The best overloaded method match for 'VSPackage.CPPCheckPlugin.CPPCheckPluginPackage.isVisualCppProject(string)' has some invalid arguments.

Visual Studio Professional 2017, version 15.3.5

**Comment by Keith-Albright-Bose** [comment]
I get the same isuse.
