### ISSUE TITLE
Cannot install - Missing .NET Framewok

### ISSUE THREAD

**Issue by omarben** [VioletGiraffe/cppcheck-vs-addin#173]
Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'cppcheck add-in' requires a version of the .NET Framework that is not installed.

Unfortunately the error message doesn't say what version of .NET I need.
I work on a managed machine (I can;t install this .NET)

So I would need to know what .NET I need so I can request it be installed by the admins.

**Comment by VioletGiraffe** [comment]
You need 4.6.
