### ISSUE TITLE
Infinite loop when saving file, if cppcheck not found

### ISSUE THREAD

**Issue by claremacrae** [VioletGiraffe/cppcheck-vs-addin#182]
Preconditions:

* install cppcheck-vs-addin 
* in the cppcheck-vs-addin settings, enable "Cppcheck start analysis when file is saved", and then save a file
* forget to install Cppcheck (because http://cppcheck.sourceforge.net/ is currently giving "Project web is currently offline pending the final migration of its data to our new datacenter."
* Create a file in your Project and then save it

Observed behaviour:

* A file dialog prompted for "cppcheck executable (cppcheck.exe)
* There's no way to break out of it - each time you Cancel, the dialog opens again

I know this was user error, but it would be noce to have more graceful behaviour, like if you click Cancel, it cancels the check, rather than keeping on asking again

**Comment by VioletGiraffe** [comment]
Fixed. That infinite loop probably wasn't such a good idea, huh.

By the way, you can download cppcheck from Github releases: https://github.com/danmar/cppcheck/releases

**Comment by claremacrae** [comment]
Wow - that's a really quick bug-fix, and thanks for the pointer to the download page too!

**Comment by VioletGiraffe** [comment]
It really was a quick fix :) You've put more effort into structuring your error report than I did into fixing it. Wish everyone would be as thorough and detailed when reporting issues.
