### ISSUE TITLE
Exclude certain files from checking

### ISSUE THREAD

**Issue by AHUMANTHATISHUMAN** [VioletGiraffe/cppcheck-vs-addin#184]
When running a check that is not an automatic check after saving, there is no way to exclude the 10000+ line libraries, resulting in 90% CPU and a very unresponsive visual studio. This makes it very difficult to cancel. There should be a way to exclude certain files or allow checking without #includes so it doesn't take hours.

**Comment by VioletGiraffe** [comment]
It's in the plugin settings. You can add filters to exclude files and folders, separately for headers and source files.
