### ISSUE TITLE
Visual Studio 2017 not works after install latest cppcheck plugin

### ISSUE THREAD

**Issue by Karaulov** [VioletGiraffe/cppcheck-vs-addin#194]
Visual Studio 2017 not works after install latest cppcheck plugin

After run, after 5-10 seconds, Visual Studio not answering and stop works.

**Comment by VioletGiraffe** [comment]
By "latest", do you mean the most recent release or the latest revision from the master branch?

**Comment by Karaulov** [comment]
@VioletGiraffe latest from ci.appveyor

**Comment by Karaulov** [comment]
I download with 'Dark theme fix' release and it works.

**Comment by VioletGiraffe** [comment]
I know about that, it's work in progress. But thanks for letting me know :)
