### ISSUE TITLE
How can I exclude complete folder from check

### ISSUE THREAD

**Issue by sparkskapil** [VioletGiraffe/cppcheck-vs-addin#195]

**Comment by VioletGiraffe** [comment]
Hm, there doesn't seem to be such an option. You can exclude files by file names (not by full path), and you can exclude include paths, but not source files based on their folder.

**Comment by sparkskapil** [comment]
Thanks for the reply.
I found a way to exclude a folder by using regex in Excluded Include paths
.*3ndParty.*
This will exclude all files in folder named 3rdParty
