### ISSUE TITLE
Excluded include paths not working

### ISSUE THREAD

**Issue by dagophil** [VioletGiraffe/cppcheck-vs-addin#201]
I added `.*gtest.*` and `.*gmock.*` to the excluded include paths. However, if I use `#include <gmock/gmock.h>` in some .cpp, I get a lot of analysis results for files coming from that include, for example, gmock-matchers.h.
I am using the addin 1.3.6 with Visual Studio Professional 2015 version 14.0.25431.01 Update 3.

**Comment by VioletGiraffe** [comment]
I think it may be a regex syntax issue. Unfortunately, regular expressions is not my strong suite, and I don't know C# specifics.

**Comment by dagophil** [comment]
Thanks for the quick reply :)
After some investigation I come to the conclusion that I probably misunderstood the purpose of the excluded include paths setting. I thought that the setting applies to the path `xyz.h` from the `#include <xyz.h>` in my source files. However, it seems that the field applies to the _Additional Include Directories_ of the project settings instead. Is that true? In that case this issue can be closed.

**Comment by VioletGiraffe** [comment]
Oh! I keep forgetting about that distinction myself. Yes, you're right. So if you specify Google Test and Mock paths via _Additional Include Directories_ you can exclude it that way, otherwise cppcheck processes the whole file as it's stored on the disk.

**Comment by dagophil** [comment]
Okay, thanks for the clarification.
