### ISSUE TITLE
The extension with the identifier "127d8bd3-8cd7-491a-9a63-9b4e89118da9" is not installed in Visual Studio Community 2017

### ISSUE THREAD

**Issue by Karaulov** [VioletGiraffe/cppcheck-vs-addin#202]
Error The extension with the identifier "127d8bd3-8cd7-491a-9a63-9b4e89118da9" is not installed in Visual Studio Community 2017

https://pastebin.com/yQzrTCA5

**Comment by VioletGiraffe** [comment]
> Не удается найти зависимый пакет "Microsoft.VisualStudio.Product.Community,version=15.9.28307.665"

What's the edition and version of your Visual Studio 2017?

**Comment by Karaulov** [comment]
@VioletGiraffe  Visual Studio Community Edition 2017, version 15.9.12

**Comment by VioletGiraffe** [comment]
> Component.Microsoft.Windows.DriverKit,version=10.0.17740.0
IF I'm reading correctly, this is what it fails to find, although I don't see how the add-in could require it. Could it be that your VS installation is somehow broken? I really don't understand.

**Comment by Karaulov** [comment]
It possible. I have installed WDK, but remove it some time ago.
