### ISSUE TITLE
Add support of  VS 2019

### ISSUE THREAD

**Issue by aliha** [VioletGiraffe/cppcheck-vs-addin#204]
It seems that version 1.4.1 does not work with Visual Studio 2019 16.2.3 .
It is installed without any error. 
When I run it, nothing happens. There is no message in `cppcheck analysis output` and `cppcheck analysis results` is empty.

**Comment by VioletGiraffe** [comment]
I don't know what problem this is yet, but I doubt it has to do with the particular version of VS  (I'm running 16.2.3 myself right now).

**Comment by aliha** [comment]
Thank you for the quick reply. 
Is there anything that I do to get more information? Any debug flag that I turn on? any log?

**Comment by VioletGiraffe** [comment]
Not really, the only way of debugging right now is to actually debug it (build from source and launch debugging).

**Comment by VioletGiraffe** [comment]
Try checking a different project / solution, as a test.

**Comment by aliha** [comment]
I tried different projects and solutions. They are the same, nothing happens.
