### ISSUE TITLE
excluding entire folders to scan

### ISSUE THREAD

**Issue by graemekelly** [VioletGiraffe/cppcheck-vs-addin#205]
Hi,

I have a solution where I want to exclude an entire folder; our code has third-party headers in /<project>/thirdparty/whatever and this pattern repeats through our code. I'd like to be able to exclude it all with one regex - .*thirdparty.*

However, the code processing the file exclusions only operates on the fileName, not the filePath:

https://github.com/VioletGiraffe/cppcheck-vs-addin/blob/599c12eb6740c75616a26e70e0a3429f7bd36019/CPPCheckPlugin/AnalyzerCppcheck.cs#L152

Do you think it would be OK to change this, or perhaps even add another set of exclusions, specifically for file path filtering?

**Comment by VioletGiraffe** [comment]
That would be great. A separate rule for paths would, of course, be the most flexible way, but I don't know if it's justified or overkill.

**Comment by graemekelly** [comment]
Yeah, seems like overkill to me tbh but I've never used the exclusions before. Happy with a PR to just change to filePath and we can worry another time if anyone comes back and says they need a separate option?

**Comment by VioletGiraffe** [comment]
Agreed, I'll happily accept the PR.

**Comment by graemekelly** [comment]
My git skills are failing me, since I have those unmerged changes for the other issue we are talking. I'll hold off on this until we decide whether I should submit a PR for the other fixes or throw them away based on your unfinished refactoring work.

**Comment by VioletGiraffe** [comment]
Submit everything then (in two separate PRs if you can).
