### ISSUE TITLE
Question: does this addin work with VSCode remote development

### ISSUE THREAD

**Issue by desmond-dsouza** [VioletGiraffe/cppcheck-vs-addin#208]
e.g. If I am running VSCode on my Mac and using `VSCode Remote SSH` to do my builds on a remote Linux box, can I still use this add-in to get static analysis checks (presumably these have to run on the remote Linux box)?

Thanks!

**Comment by VioletGiraffe** [comment]
I don't think so. VS Code is totally different from the proper Visual Studio, their plugins are not compatible in any way.
