### ISSUE TITLE
Latest release is too old

### ISSUE THREAD

**Issue by phuclv90** [VioletGiraffe/cppcheck-vs-addin#209]
The latest release in https://github.com/VioletGiraffe/cppcheck-vs-addin/releases/latest and https://marketplace.visualstudio.com/items?itemName=Alexium.Cppcheckadd-in is 1.3.6 and doesn't work in VS 2019. I tried to compile from source and it came out being 1.4.1

**Comment by BitCruncher0** [comment]
> 
> 
> The latest release in https://github.com/VioletGiraffe/cppcheck-vs-addin/releases/latest and https://marketplace.visualstudio.com/items?itemName=Alexium.Cppcheckadd-in is 1.3.6 and doesn't work in VS 2019. I tried to compile from source and it came out being 1.4.1

Does 1.4.1 work on VS 2019?

**Comment by VioletGiraffe** [comment]
Yes, it does work on VS 2019.

**Comment by amai2012** [comment]
@VioletGiraffe  Is there a specific reason for not providing more recent release?

**Comment by VioletGiraffe** [comment]
@amai2012, none. I've been working on a deep refactoring and was going to update the release when I'm done, but I got stuck up to the point where even basic VS SDK calls didn't work at all and I couldn't understand why. So I guess I just need to revert everything.

**Comment by VioletGiraffe** [comment]
There is now a fresh release with VS 2019 support.

**Comment by GitMensch** [comment]
@VioletGiraffe Can you please push the new release to https://marketplace.visualstudio.com/items?itemName=Alexium.Cppcheckadd-in? it is still on version 1.3.4.

**Comment by VioletGiraffe** [comment]
@GitMensch, sure, will do. Good point.
