### ISSUE TITLE
Appears to do nothing.

### ISSUE THREAD

**Issue by ncook-hxgn** [VioletGiraffe/cppcheck-vs-addin#212]
Hi there, 

I installed CppCheck and then this extension. I have a 'cppcheck analysis output' stream available in my Visual Studio Output window, however when I CppCheck Current Project, nothing happens. What gives?

The extension didn't ask for CppCheck's location. 

Edit: I am able to use CppCheck via it's CLI successfully, generating output xmls files etc.

Surely this is some error on my behalf?

**Comment by VioletGiraffe** [comment]
It's hard to say without debugging. Could be that something in the project structure or settings prevents the VS add-in from reading the project or from interpreting it as a C++ project. You could try a different project from a different source (some simple open-source tool from Github, for example. I used to use the LLVM solution for testing).

**Comment by ncook-hxgn** [comment]
I will give the LLVM solution a go (didn't realise it I could just install it with VS before I started building it!)

Thanks for the speedy respone - apologies for taking a few days to get back to you.

**Comment by VioletGiraffe** [comment]
> Are there any secret-squirrel logging features available for the plugin?
Unfortunately, not. I didn't encounter many problems for which logging could be helpful. But clearly, it's time to add some. I'll look into it right now.

**Comment by VioletGiraffe** [comment]
I seem to have the same problem, the code for determining types of items in a project doesn't work the way it used to. I'm looking into it.

**Comment by ncook-hxgn** [comment]
That's great news. It would be awesome to have this working in VS alongside Clang-Tidy and MS Code Analysis 💪

**Comment by VioletGiraffe** [comment]
To be honest, I'm disappointed in cppcheck - a big part of the reason why I haven't actively developed this extension for a long while. Cppcheck doesn't hold a candle to clang.

Try the attached extension: 
[CppcheckPlugin.zip](https://github.com/VioletGiraffe/cppcheck-vs-addin/files/5811042/CppcheckPlugin.zip)

**Comment by ncook-hxgn** [comment]
That's a bit disheartening to hear about cppcheck! Howcomes?

I renamed the zip to .vsix, and got an installation error.. it says it's missing an extension.vsixmanifest..

**Comment by VioletGiraffe** [comment]
You need to extract the VSIX file from the ZIP archive, not just rename it :)

**Comment by ncook-hxgn** [comment]
Ahaa, you got me! 

So I am curious although it's off topic - what do prefer about Clang over CppCheck?

**Comment by VioletGiraffe** [comment]
Cppcheck seems to suffer from not being an actual compiler, and also from having a very small development team. Failures to find includes, especially the system ones (Windows SDK), sometimes errors interpreting valid C++ syntax. Also, there could be way more different useful checks. 
But don't be disheartened by my rambling, any static analysis tool is better than no tool, and the more you use simultaneously - the better.

**Comment by ncook-hxgn** [comment]
That all makes sense to me! From what I remember of reading the CppCheck blurb on their website, they do say they have a slimmer focus, with their tool. I agree entirely, we'll need to figure out which tools serve us best for certain checks and work with them accordingly. Horses for Courses as they say 👍 I am just glad we are in a place now with VS where I can get three tools into developers hands for free - that's a long way from where we've been historically.

I've installed the extension from the zip, still no output I'm afraid. (It reports 1.4.3 as version). I'm attempting to scan LLVM.sln's clang executables/diagtool.vcxproj.

**Comment by VioletGiraffe** [comment]
1.4.3 is the updated version indeed. Odd, since I was able to reproduce the error and then I fixed it. I guess I can't get away without proper debug logging after all. It'll take a bit because I don't have much free time these days, but I'll get back to you.

**Comment by ncook-hxgn** [comment]
Sure thing :) I appreciate how responsive you've been, and there's no immediate rush - I am very much in the researching phase at the moment. 

FWIW I'm using VS 2019 16.7.3 on a recently updated x64 Windows 10 Pro box (probably should have mentiond that earlier). 

If you need a tester, I am here and happy to help - it doesn't take long to install the extension, open the LLVM solution, and have a go with it.

**Comment by CasperLuca** [comment]
I had a similar experience, (perhaps after i changed my supression file?!? or some other setting in the interface, I was fiddeling arround a bit before I noticed) the extension stopped working, but in my case updating to your 1.4.3 zip fixed the issue. 

though I was able to reproduce something similar afterwards: if I add something incorrect to the solution suppression file under [cppcheck_files] or [cppcheck_includes] like */foldername/* i would expect nothing to change, but the only output becomes: Looking for C++ source files in the project "projectname"

I am under the impression */foldername/* should be ./foldername/. ? but then cppcheck behaves the same as when putting nothing in the suppresion file.

**Comment by SpareSimian** [comment]
Still no output with VS 2019 16.10.3 on Win10 x64 21H1. I figured I'd get either a dialog or output in the log window showing analysis progress. 

I might see if I can get this to build. I haven't investigated implementing an IDE extension before so the attempt should be interesting.

(I recently discovered the cppstories.com blog (good for advanced C++ programmers) and saw mention of the SonarSource static analyzer in his weekly newsletter. When I looked up static analyzers, I found cppcheck, and looking for VS integration led me here.)

**Comment by SpareSimian** [comment]
I cloned/built/installed and the current master fixes the problem for me, using VS 16.10.4.

**Comment by VioletGiraffe** [comment]
Interesting, thanks for the info. I'll check what it was that the master fixed over the last release and will then update the release.

Although there's non-zero chance that it worked simply because you built it locally, and didn't work because there's something wrong with the references in my binary package when it runs in your VS.

**Comment by SpareSimian** [comment]
I unloaded my version and tried the one from your January zip file and that does nothing, as with 1.4.2. So it sounds like the build environment might be a factor.

**Comment by SpareSimian** [comment]
Both my Release and Debug builds produce output. So it's not the configuration.

**Comment by VioletGiraffe** [comment]
[CppcheckPlugin (2).zip](https://github.com/VioletGiraffe/cppcheck-vs-addin/files/6926670/CppcheckPlugin.2.zip)
Please try this VSIX I just built from master head on my machine, does it work?

**Comment by VioletGiraffe** [comment]
Well, I've installed it on my dev machine and it does nothing, so there is indeed something fishy going on. I'll investigate.

**Comment by yuyoyuppe** [comment]
@VioletGiraffe that one also didn't work for me :)

**Comment by VioletGiraffe** [comment]
@yuyoyuppe, are you able to build the extension from source to confirm that the problem is related to the build environment/settings and not the source code itself?

**Comment by yuyoyuppe** [comment]
Yep, building current master worked for me, so it's definitely something with your env

**Comment by VioletGiraffe** [comment]
What about the package built by Github? 
https://github.com/VioletGiraffe/cppcheck-vs-addin/suites/3451024510/artifacts/81918205

**Comment by yuyoyuppe** [comment]
@VioletGiraffe that one does work, thank you.

Although the tool itself didn't produce any useful results unfortunately :(

**Comment by VioletGiraffe** [comment]
@yuyoyuppe, maybe you didn't have enough errors in your code :)
Thank you for letting me know the version built by Github VM works.
