### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by roalz** [VioletGiraffe/cppcheck-vs-addin#217]
Can this extension be updated to support Visual Studio 2022?

**Comment by VioletGiraffe** [comment]
I hope so, but haven't looked into that yet.

**Comment by netmonitoring** [comment]
VioletGiraffe, could you take a look for VS2022 support? Thanks.

**Comment by arsari** [comment]
I wish to have this on my VS 2022 for a current work in progress for the next weeks...

**Comment by VioletGiraffe** [comment]
I gave it a quick try. Bumping the upper supported VS version to 17 in the vsixmanifest produces a VSIX file that's not installable in both 2019 and 2022. I've tried both ways - `18)` and `17]`.

**Comment by Ou7law007** [comment]
Is it coming to VS 2022 at all at this point?

**Comment by VioletGiraffe** [comment]
Can you make it happen? I couldn't.

**Comment by Ou7law007** [comment]
I don't have the knowledge or experience to do it unfortunately.

**Comment by VioletGiraffe** [comment]
I am quite curious as to why simply bumping the target VS version doesn't work (it did with the transition from 2017 to 2019), and why the resulting VSIX is not installable even in Vs2019. Could someone please explain this?

**Comment by ReggThims** [comment]
On 17/03/2022 23:04, Violet Giraffe wrote:
>
> I am quite curious as to why simply bumping the target VS version 
> doesn't work (it did with the transition from 2017 to 2019), and why 
> the resulting VSIX is not installable even in Vs2019. Could someone 
> please explain this?
>
https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by t-johnson** [comment]
@VioletGiraffe i can try to take this on.  i've done this for another extension i built...

**Comment by VioletGiraffe** [comment]
@t-johnson, please, be my guest! That would be great.

**Comment by t-johnson** [comment]
@VioletGiraffe 
Okay creating a branch for VS2019 sounds great. i am getting the current project converted to target VS2022, upgrading nuget packages, etc.  once i have done some testing i will make a PR for you.

**Comment by BoraxKid** [comment]
Can a new release also be made available for VS2022 please ?

**Comment by VioletGiraffe** [comment]
@BoraxKid, get the add-in from Appveyor: https://ci.appveyor.com/api/buildjobs/3pan1uvrvx744gmm/artifacts/CPPCheckPlugin%2Fbin%2FRelease%2FCppcheckPlugin.vsix
Later I'll make a release, too.

**Comment by songzi-w** [comment]
> @BoraxKid, get the add-in from Appveyor: https://ci.appveyor.com/api/buildjobs/3pan1uvrvx744gmm/artifacts/CPPCheckPlugin%2Fbin%2FRelease%2FCppcheckPlugin.vsix Later I'll make a release, too.

Can't download it?

**Comment by VioletGiraffe** [comment]
@BoraxKid I've made a release: https://github.com/VioletGiraffe/cppcheck-vs-addin/releases/tag/1.5
