### ISSUE TITLE
Wrong conclusions by cppcheck?

### ISSUE THREAD

**Issue by Ou7law007** [VioletGiraffe/cppcheck-vs-addin#220]
This is simply not true.

![image](https://user-images.githubusercontent.com/64309267/162510325-8a537e72-59c1-4550-96be-8f6184352d70.png)

**Comment by VioletGiraffe** [comment]
This is a problem of the cppcheck tool, not my extension which is just a wrapper for cppcheck. Report it to the cppcheck maintainers.
