### ISSUE TITLE
will this plugin connect with cxx community rules in SonarQube

### ISSUE THREAD

**Issue by fayaz988** [VioletGiraffe/cppcheck-vs-addin#228]
I am using SonarQube Community edition with third party cxx plugin for C++ rules, i want to see the same rules on visual Studio as well and at the same time i should be able to see new code issues after modifying cpp file, is it possible with this tool?

Thanks,
fayaz

**Comment by VioletGiraffe** [comment]
No, this add-in is for cppcheck, not for SonarQube.
