### ISSUE TITLE
VS2013 Carsh at check end

### ISSUE THREAD

**Issue by lohengrin** [VioletGiraffe/cppcheck-vs-addin#99]
The plugin crash VS2013 at the end of many (not all) of my projects.
I succeed to reproduce the bug using debug version, but my level in C# and VS SDK is quite limited and I do not understand why it crash here.
![cppcheck-vsaddin](https://cloud.githubusercontent.com/assets/2031871/5391510/3706ac42-811c-11e4-9380-95729b0453b4.png)

So if someone can help me to solve it....

**Comment by VioletGiraffe** [comment]
Fixed in a484b0f9056f951c735de4ad5e68b564749893e7.
